### ISSUE TITLE
CIS Pilot Blows Up flask-pyoidc

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#162]
For users in the cis_whitelist ( at least me ) the sso-dashboard does not work after app.metadata integration.  I removed my app_metadata and could login after. 

So I'm assuming there's something that can not be flattened by flask-pyoidcs to_dict() method.

@gdestuynder and I can look at this tomorrow.  

[2017-08-17 23:15:07,620] ERROR in app: Exception on /redirect_uri [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 115, in _handle_authentication_response
    flask.session['userinfo'] = userinfo.to_dict()
  File "/usr/lib/python2.7/site-packages/oic/oauth2/message.py", line 314, in to_dict
    elif isinstance(val, list) and isinstance(val[0], Message):
IndexError: list index out of range[2017-08-17 23:17:19,786] ERROR in app:

**Comment by andrewkrug** [comment]
The workaround for this has landed in prod. @gdestuynder @hmitsch  we are no longer blocked adding people to the CIS whitelist due to dashboard.

**Comment by hmitsch** [comment]
Great news, @andrewkrug. Thank you!
