### ISSUE TITLE
Unicode causes a problem serializing auth0 profile to user['session']

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#178]
This was reported last night by the Taipei office.  I can reproduce the problem simply by adding a single unicode character to my name.

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 256, in _handle_authentication_response
    authn_resp['state'], self.userinfo_endpoint_method
  File "/usr/lib/python2.7/site-packages/flask_pyoidc/flask_pyoidc.py", line 277, in _do_userinfo_request
    method=userinfo_endpoint_method, state=state
  File "/usr/lib/python2.7/site-packages/oic/oic/__init__.py", line 890, in do_user_info_request
    logger.debug("Reponse text: '%s'" % sanitize(resp.text))
  File "/usr/lib/python2.7/site-packages/oic/utils/sanitize.py", line 45, in sanitize
    potentially_sensitive = str(potentially_sensitive)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 28-30: ordinal not in range(128)

**Comment by dividehex** [comment]
The dashboard currently executes on a python 3.x environment and which doesn't suffer from this bug.
