### ISSUE TITLE
auth0 integration failing claims

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#3]
Traceback (most recent call last):
  File "/Users/akrug/workspace/sso-dashboard/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/akrug/workspace/sso-dashboard/tests/unit/test_op_authzero.py", line 55, in test_token_decoding
    decoded_payload = decoder.decode(os.environ['AUTH0_SIGNING_SECRET'])
  File "/Users/akrug/workspace/sso-dashboard/dashboard/op/authzero.py", line 22, in decode
    algorithms=['HS256']
  File "/Users/akrug/workspace/sso-dashboard/lib/python2.7/site-packages/jwt/api_jwt.py", line 75, in decode
    self._validate_claims(payload, merged_options, **kwargs)
  File "/Users/akrug/workspace/sso-dashboard/lib/python2.7/site-packages/jwt/api_jwt.py", line 98, in _validate_claims
    self._validate_iat(payload, now, leeway)
  File "/Users/akrug/workspace/sso-dashboard/lib/python2.7/site-packages/jwt/api_jwt.py", line 129, in _validate_iat
    raise InvalidIssuedAtError('Issued At claim (iat) cannot be in'
InvalidIssuedAtError: Issued At claim (iat) cannot be in the future.

**Comment by andrewkrug** [comment]
auth0 won't fix
