### ISSUE TITLE
Dashboard does not handle case where it can not detect if firefox is latest

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#316]
```
[2018-07-10 19:16:00,846] ERROR in app: Exception on /dashboard [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.4/site-packages/flask_pyoidc/flask_pyoidc.py", line 318, in wrapper
    return view_func(*args, **kwargs)
  File "/sso-dashboard/app.py", line 182, in dashboard
    Rules(userinfo=session['userinfo'], request=request).run()
  File "/sso-dashboard/models/alert.py", line 286, in run
    self.alert_firefox_out_of_date()
  File "/sso-dashboard/models/alert.py", line 289, in alert_firefox_out_of_date
    if self._firefox_out_of_date():
  File "/sso-dashboard/models/alert.py", line 343, in _firefox_out_of_date
    f_version = self._version_to_dictionary(self._firefox_info().get('LATEST_FIREFOX_VERSION'))
  File "/sso-dashboard/models/alert.py", line 316, in _firefox_info
    return release_json.json()
  File "/usr/lib/python3.4/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by andrewkrug** [comment]
https://github.com/mozilla-iam/sso-dashboard/pull/318

This bandaids this.  We'll need to handle the 404 and abort.  This should be done in a subsequent patch.
