### ISSUE TITLE
sso.allizom.org doesn't find cdn 

### ISSUE THREAD

**Issue by andrewkrug** [mozilla-iam/sso-dashboard#349]
```
[2018-11-07 17:13:49 +0000] [17] [INFO] Worker exiting (pid: 17)
flask_pyoidc.flask_pyoidc
[2018-11-07 17:13:49 +0000] [14] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python3.4/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.4/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.4/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.4/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/sso-dashboard/dashboard/app.py", line 23, in <module>
    from dashboard import config
  File "/sso-dashboard/dashboard/config.py", line 19, in <module>
    class DefaultConfig(object):
  File "/sso-dashboard/dashboard/config.py", line 35, in DefaultConfig
    CDN = CONFIG('cdn', namespace='sso-dashboard', default='https://cdn.{SERVER_NAME}'.format(SERVER_NAME=SERVER_NAME))
  File "/usr/lib/python3.4/site-packages/everett/manager.py", line 927, in __call__
    val = env.get(possible_key, use_namespace)
  File "/sso-dashboard/dashboard/__init__.py", line 41, in get
    region="us-east-1"
  File "/usr/lib/python3.4/site-packages/credstash.py", line 493, in getSecret
    raise ItemNotFound("Item {'name': '%s'} couldn't be found." % name)
credstash.ItemNotFound: Item {'name': 'sso-dashboard.cdn'} couldn't be found.
[2018-11-07 17:13:49 +0000] [14] [INFO] Worker exiting (pid: 14)
flask_pyoidc.flask_pyoidc
[2018-11-07 17:13:49 +0000] [15] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.4/site-packages/gunicorn/workers/ggevent.py", line 190, in init_process
    super(GeventWorker, self).init_process()
  File "/usr/lib/python3.4/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.4/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.4/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.4/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.4/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/sso-dashboard/dashboard/app.py", line 23, in <module>
    from dashboard import config
  File "/sso-dashboard/dashboard/config.py", line 19, in <module>
    class DefaultConfig(object):
  File "/sso-dashboard/dashboard/config.py", line 35, in DefaultConfig
    CDN = CONFIG('cdn', namespace='sso-dashboard', default='https://cdn.{SERVER_NAME}'.format(SERVER_NAME=SERVER_NAME))
  File "/usr/lib/python3.4/site-packages/everett/manager.py", line 927, in __call__
    val = env.get(possible_key, use_namespace)
  File "/sso-dashboard/dashboard/__init__.py", line 41, in get
    region="us-east-1"
  File "/usr/lib/python3.4/site-packages/credstash.py", line 493, in getSecret
    raise ItemNotFound("Item {'name': '%s'} couldn't be found." % name)
credstash.ItemNotFound: Item {'name': 'sso-dashboard.cdn'} couldn't be found.
```

**Comment by dividehex** [comment]
Since migrating to GCP, the dashboard app no longer uses credstash.
